# We're using version 3.7 of the Docker Compose file format
version: "3.7"

# Define services/containers
services:
  # MySQL container
  mysql:
    # Use mysql:latest image
    image: mysql:latest
    # Data folder
    volumes:
      - /home/rustmod/feedbackform/docker-laravel8/mysql-data/:/var/lib/mysql
    # Connect to "drfoxg-net" network, as defined below
    networks:
      - drfoxg-net
    # Pass a list of environment variables to the container
    environment:
      MYSQL_ROOT_PASSWORD: go7856go

  # phpMyAdmin container
  phpmyadmin:
    # Use phpmyadmin/phpmyadmin:latest image
    image: phpmyadmin/phpmyadmin:latest
    # Connect to "drfoxg-net" network, as defined below
    networks:
      - drfoxg-net
    # Map port 8080 on the host to port 80 inside the container
    # Syntax is: "HOST_PORT:CONTAINER_PORT"
    ports:
      - "8080:80"
    # Pass a list of environment variables to the container
    environment:
      PMA_HOST: mysql
    # Wait for "mysql" container to start first
    depends_on:
      - mysql
      
  # laravel 8 + vue 2 container
  laravel8:
    image: drfoxg/laravel8
    build:
      context: ../docker-laravel8
    volumes:
      - /home/rustmod/feedbackform/docker-laravel8/www/:/var/www/laravel8
    networks:
      - drfoxg-net
    ports:
      - "80:80"
    environment:
       XDEBUG_CONFIG: remote_host=192.168.1.90

# Define networks
networks:
  drfoxg-net:
