# We're using version 3.7 of the Docker Compose file format
version: "3.7"

# Define services/containers
services:
  # MySQL container
  mysqllaravel8:
    # Use mysql:latest image
    image: mysql:latest
    # Data folder
    volumes:
      - /home/rustmod/feedbackform/docker-laravel8/mysql-data/:/var/lib/mysql
    # Connect to "drfoxg-net" network, as defined below
    networks:
      - drfoxg-net
    # Pass a list of environment variables to the container
    environment:
      MYSQL_ROOT_PASSWORD: secret

  # laravel 8 + vue 2 container
  laravel8:
    image: drfoxg/laravel8
    build:
      context: ../docker-laravel8
    volumes:
      - /home/rustmod/feedbackform/docker-laravel8/www/:/var/www/laravel8
      - /home/rustmod/feedbackform/docker-laravel8/www1/:/var/www/crossword
    networks:
      - drfoxg-net
    ports:
      - "80:80"
    cap_add:
       - ALL
    environment:
       XDEBUG_CONFIG: remote_host=192.168.1.90

# Define networks
networks:
  drfoxg-net:
